#!/usr/bin/env bash

#################################################
#
# System install
# 
# Terminal - Zsh
# 
# Theme    - Spaceship (Requires Nerd Font)
#
################################################


system_type=$(uname -s)

if [ $system_type = "Darwin" ]
then
    echo
    echo "--------------------------------------------------"
    echo "=-=-=-=-=-= Mac System Installation =-=-=-=-=-="
    echo "--------------------------------------------------"
    echo
    # Module for Mac
fi

if [ $system_type = "Linux" ]
then
    echo
    echo "-------------------------------------------------"
    echo "=-=-=-=-=-= Linux System Installation =-=-=-=-=-="
    echo "-------------------------------------------------"
    echo 
    # Modules for Linux
fi

# Modules for both mac and linux

read -p '[*] tmux.conf install? [Y/n] ' install_tmux
install_tmux=${install_tmux:-Y}
read -p '[*] vimrc install? [Y/n] ' install_vim
install_vim=${install_vim:-Y}
read -p '[*] zshrc install? [Y/n] ' install_zsh
install_zsh=${install_zsh:-Y}
read -p '[*] alacritty.yml install? [Y/n] ' install_alacritty
install_alacritty=${install_alacritty:-Y}
read -p '[*] Xresources install? [Y/n] ' install_X
install_X=${install_X:-Y}

if [ $install_tmux != 'n' ] && [ $install_tmux != 'N' ] 
then
    if [ -f ~/.tmux.conf ]
    then
        echo "[!!!] File already exists on system (tmux.conf)"
    else
        echo "===> Linking tmux configurations"
        ln -s ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
    fi
fi

if [ $install_vim != 'n' ] && [ $install_vim != 'N' ]
then
    if [ -f ~/.vimrc ]
    then
        echo "[!!!] File already exists on system (vimrc)"
    else
        echo "===> Linking vim configurations"
        ln -s ~/dotfiles/vim/vimrc ~/.vimrc
    fi
fi

if [ $install_zsh != 'n' ] && [ $install_zsh != 'N' ]
then
    if [ -f ~/.zshrc ]
    then
        echo "[!!!] File already exists on system (zshrc)"
    else
        echo "===> Linking zsh configurations"
        ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
    fi
fi

if [ $install_alacritty != 'n' ] && [ $install_alacritty != 'N' ]
then
    if [ -f ~/.config/alacritty.yml ]
    then
        echo "[!!!] File already exists on system (alacritty.yml)"
    else
        echo "===> Linking alacritty configurations"
        ln -s ~/dotfiles/alacritty/alacritty.yml ~/.config/alacritty.yml
    fi
fi 

if [ $install_X != 'n' ] && [ $install_X != 'N' ]
then
    if [ -f ~/.Xresources ]
    then
        echo "[!!!] File already exists on system (Xresources)"
    else
        echo "===> Linking X server configurations"
        ln -s ~/dotfiles/X/Xresources ~/.Xresources
    fi
fi

# Download oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Download autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Download syntex highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Download and install shapship theme
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# Download and install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git  ~/.vim/bundle/Vundle.vim

# Download and install a nerd font
git clone https://github.com/ryanoasis/nerd-fonts.git
./nerd-fonts/install.sh 'SauceCodePro Nerd Font Complete Mono'
rm -rf nerd-fonts

# Download and install Tmux theme
git clone https://github.cim/jihem/tmux-themepack.git ~/.tmux-themepack
source "${HOME}/.tmux-themepack/powerline/block/blue.tmuxtheme"

echo
echo "[+] Install Complete"
echo

