"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Johannes Naylor"
email = "jonaylor89@gmail.com"

[aliases]
# tug: bring nearest bookmark up to recent commit
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# retrunk:
# `jj rebase -d 'trunk()'` is shorthand for `jj rebase -b @ -d 'trunk()'`
#
# What that does:
#
# `-b @` rebases the entire branch that the current @ is on relative to the destination. (Default),
# `-d trunk()` sets the destination. trunk() finds the most recent `main | master | trunk` branch thats on a remote. trunk() is builtin.
retrunk = ["rebase", "-d", "trunk()"]

# Gitconfig-style aliases
# dm: describe current change with a message (like git cim)
dm = ["describe", "-m"]
cl = ["git", "clone"]
ps = ["git", "push"]
ra = ["git", "remote", "add"]
rao = ["git", "remote", "add", "origin"]
tree = ["log", "-r", "::"]

# JJ-native shortcut used frequently
bs = ["bookmark", "set"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

# From mitchellh
[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
diff-editor = ":builtin"
merge-editor = ":builtin"
