#!/usr/bin/env bash

########################################
#                                      #
# YOU MUST HAVE HOMEBREW INSTALLED!!!! #
#                                      #
########################################

brew install zsh \
            git \
            curl 

brew tap koekeishiya/formulae
brew install --HEAD chunkwm


