#!/usr/bin/env bash

########################################
#                                      #
# YOU MUST HAVE HOMEBREW INSTALLED!!!! #
#                                      #
########################################

brew install zsh git curl 

