
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    guifont = "JetBrainsMono Nerd Font Regular:h14"
    statusline_separator = "curve"
    statusline_inactive_separator = "curve"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    # Enable automatic updates
    automatic_update = 1

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 31

[[layers]]
name = 'colorscheme'

[[layers]]
name = "lang#python"
format_on_save = 1

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#dart"

[[layers]]
name = "lang#javascript"
auto_fix = true

[[layers]]
name = "lang#swift"

[[custom_plugins]]
name = "ctrlpvim/ctrlp.vim"
