
- 
  name: MacOS Desktop Configuration
  hosts: localhost
  pre_tasks:
    - name: Create directory for repositories
      file: 
        path: '{{ ansible_env.HOME }}/Repos'
        state: directory
        mode: '0755'
