
- 
  name: Ubuntu Desktop Configuration
  hosts: localhost
  tasks:
      - name: Install apt packages
        include_role:
            name: apt

      - name: Install snap packages
        include_role: 
          name: snap

      - name: Install rust
        include_role:
          name: rust

      - name: install starship.rs
        shell: curl -fsSL https://starship.rs/install.sh | bash
        args:
          warn: false

        
            
